name: ARM PyInstaller Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-rpi:
    name: Build (rpi-aarch64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build on ARM (QEMU)
        uses: pguyot/arm-runner-action@v2
        with:
          cpu: cortex-a72
          base_image: raspios_lite_arm64:latest
          image_additional_mb: 1024
          shell: bash
          copy_artifact_path: "dist"
          commands: |
            set -eux

            echo "System info:"
            uname -a
            python3 --version

            sudo apt-get update
            sudo apt-get install -y \
              python3 \
              python3-tk \
              git

            wget -qO- https://astral.sh/uv/install.sh \
              | env UV_UNMANAGED_INSTALL="$HOME/.local/bin/" sh
            $HOME/.local/bin/uv sync --group build --no-dev

            .venv/bin/pyinstaller main.spec

            ls -laF
            ls -laF dist

      - name: Package Artifact
        run: |
          sudo chown -R "$USER:" dist
          cd dist
          tar -czf pyinstaller-rpi-test-aarch64.tar.gz pyinstaller-rpi-test

      - name: Check Directory
        run: |
          ls -laF
          ls -laF dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyinstaller-rpi-test
          path: dist/pyinstaller-rpi-test-aarch64.tar.gz
