name: ARM PyInstaller Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build on ARM (QEMU)
        uses: pguyot/arm-runner-action@v2
        with:
          #image: raspios_lite_arm64
          #cpu: cortex-a72
          #base_image: raspios_lite_arm64
          #shell: bash
          copy_artifact_path: "dist"
          commands: |
            set -eux

            echo "System info:"
            uname -a
            python3 --version

            wget -qO- https://astral.sh/uv/install.sh | sh
            uv sync --group build --no-dev

            .venv/bin/pyinstaller main.spec

            ls -laF
            ls -laF dist

      - name: Upload ARM artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm-pyinstaller-test
          path: dist/OnSpectra
